name: ReverseCraft
version: 1.0.1
main: io.github.ann0y1nghacker.plugin.Plugin
api-version: 1.17
authors: [ANN0Y1NGHACKER]
description: Reverse Craft items in minecraft
website: ANN0Y1NGHACKER.github.io